name = "Fractalizer"
uuid = "c0cd90ba-f482-40dc-b865-bff11b43dfb3"
version = "0.1.0"
authors = ["gbene <gabri.benedetti@gmail.com>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = ">= 1.11"